#!/bin/sh

alias lg="lazygit"
alias d="docker"
alias dc="docker compose"
alias dcu="docker compose up -d"
alias dce="docker compose exec"
alias dcd="docker compose down"
alias dokcer="docker"
alias k="kubectl"
alias la="ls -la"
alias ll="ls -la"
alias gti="git"
alias igt="git"
alias c="clear"
